### ISSUE TITLE
Quest: where to find napi-async example of yours?

### ISSUE THREAD

**Issue by Globik** [JamesMGreene/napi-async-promise-example#1]
In a home directory of you cant find out where the other examples using napi.h
Im intrested in asynworker class example.
In readme one need to give the links to your simple examples.

**Comment by JamesMGreene** [comment]
I unfortunately have no idea what you are asking for here. Can you please better explain what you are seeking?

**Comment by JamesMGreene** [comment]
If you are looking for an example of using `Napi::AsyncWorker`, you can check out the "addon.cc" file in a different repo of mine: https://github.com/JamesMGreene/napi-async-callback-example

If you mean "where do these classes like `AsyncWorker` come from?", then the answer is that they are part of the [`node-addon-api` NPM module](https://www.npmjs.com/package/node-addon-api) that is roughly modeled after the "NAN" project and is built upon Node `8.x`'s new N-API.

**Comment by Globik** [comment]
Hi, I mean I 'm looking for the napi-async-callback-example. I knew it must be somewhere but not found. Yes this what I need. Thank you @JamesMGreene .
I'm also struggling it is a strong need delete the new Work? Without it it will be memory leak? OK, i'll try your example and will give you a feedback.
 One can close this issue.
